version: "3.8"
services:
  dev-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jobhub
    networks:
      - jobhub
   

networks:
  jobhub:

